[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    # content security policy - prevents xss and unauthorized resource loading
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'; frame-ancestors 'none';"
    
    # prevent clickjacking by denying iframe embedding
    X-Frame-Options = "DENY"
    
    # prevent mime type sniffing attacks
    X-Content-Type-Options = "nosniff"
    
    # control referrer information sent to external sites
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # enable xss protection in browsers
    X-XSS-Protection = "1; mode=block"
    
    # prevent loading over http when https is available
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Performance headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 